services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:latest

    environment:
      LANG: ${LANG}
      WG_HOST: ${WG_HOST}
      WG_PORT: ${WG_PORT}
      WG_DEFAULT_DNS: ${WG_DEFAULT_DNS}
      UI_TRAFFIC_STATS: ${UI_TRAFFIC_STATS}
      PASSWORD_HASH: ${PASSWORD_HASH}

    volumes:
      - ${APP_DATA_DIR}/wireguard:/etc/wireguard

    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      - "51821:51821/tcp"

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
